name: grabbito
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  connectivity: ^3.0.3
  geocoding: ^2.0.0
  geolocator: ^7.0.3
  fluttertoast: ^8.0.7
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  flutter_screenutil: ^5.0.0+2
  dotted_border: ^2.0.0
  dotted_line: ^3.0.0
  timeline_tile: ^2.0.0
  flutter_svg: ^0.22.0
  retrofit: ^2.0.0
  logger: ^1.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_spinkit: ^5.0.0
  cached_network_image: ^3.0.0
  uuid: ^3.0.4
  google_maps_flutter: ^2.0.6
  flutter_html: ^2.1.1
  razorpay_flutter: ^1.2.7
  flutter_stripe: ^2.0.1
  #  stripe_payment: ^1.1.4
  flutter_credit_card: ^2.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  scoped_model: ^2.0.0-nullsafety.0
  intl: ^0.17.0
  location: ^4.3.0
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.0.10
  flutter_switch: ^0.3.2
  onesignal_flutter: ^3.2.5
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.4
  google_maps_place_picker_mb: ^2.0.0-mb.10
  iconly:
#  google_maps_place_picker: ^2.1.0-nullsafety.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^2.0.0+3
  build_runner: ^2.0.6

  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4



#-- splash generate --
  #flutter pub run flutter_native_splash:create
  #
  #-- ic luncher generate --
  #flutter pub run flutter_launcher_icons:main

flutter_native_splash:
#  color: "#FFFFFF"
  background_image: assets/images/grabbito_splash.png
  color_dark: "#1a1a1a"
  android: true
  ios: true
#  android_gravity: fill
  android_gravity: center
  ios_content_mode: scaleAspectfill

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/profile.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Grold Black
      fonts:
        - asset: assets/fonts/Grold-Black.ttf
    - family: Grold Regular
      fonts:
        - asset: assets/fonts/Grold-Regular.ttf
    - family: Grold Bold
      fonts:
        - asset: assets/fonts/Grold-Bold.ttf
    - family: Grold XBold
      fonts:
        - asset: assets/fonts/Grold-ExtraBold.ttf
    - family: Grold Thin
      fonts:
        - asset: assets/fonts/Grold-Thin.ttf
    - family: Grold Medium
      fonts:
        - asset: assets/fonts/Grold-Medium.ttf
    - family: Grold Italic
      fonts:
        - asset: assets/fonts/Grold-Italic.ttf



  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lib/localization/languages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
